runtime: nodejs16

env_variables:
  DATABASE_URL: 'mysql://qn2lng0qwgjk0csmfa2j:pscale_pw_IfD08S91GZcqv4AZADgksqrlUNJPtSmjiV3Rbr8kg8W@aws.connect.psdb.cloud/deploy-test?sslaccept=strict'
  AUTH0_JWK_URI: "https://note-taking.us.auth0.com/.well-known/jwks.json"
  AUTH0_AUDIENCE: "https://api.notes"
  AUTH0_ISSUER: "https://note-taking.us.auth0.com"
  PORT: 8080